FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# REST API for Cinemas IS

College project which aims to create Information System for Cinemas chain

# Group Reservation

Data related to reservation system

## Data Structures

### City (object)
- id: 1 (number, required)
- name: City name (string, required)

### Cinema (object)
- id: 1 (number, required)
- name: Cinema name (string, required)
- street: Cinema street (string, required)
- postcode: 123456 (number, required)
- latitude: 40.71 (number, required)
- longtitude: 74.00 (number, required)

### Movie (object)
- id: 1 (number, required)
- name: Movie name (string, required)
- projection_times: 1541190611, 1541190611 (array[number], required) - Timestamp in seconds
- language: cz (string, required)
- subtitle: en (string, nullable)
- access: 12+ (string, nullable)
- genre: Movie genre (string, required)
- length: 155  (number, required) - Move length in minutes

## Cities Collection [/cities]

### List all cities [GET]

+ Response 200 (application/json)
    
    + Attributes (array[City])
    
## Cinemas Collection [/cinemas]

### List all cinemas [GET]

+ Response 200 (application/json)
    
    + Attributes (array[Cinema])
    
## Cinemas in Cities [/cities/cinemas]

### List all cinemas associated to cities [GET]

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - Include City
            - cinemas (array[Cinema])

## List Movies associated to cinema [/cinemas/{id}/movies]

### Cinemas  [GET]

+ Parameter
    - id (number) - Cinema id

+ Response 200 (application/json)
 
    + Attributes (array[Movie])